### ISSUE TITLE
ToDo List Partie 1

### ISSUE THREAD

**Issue by Mangawn** [Sonkom/MIPS_3A#1]
# TODOLIST PARTIE 1
Je me suis basé sur le site gladir.com mais il y a quelques différences (NOP sur le site est indiqué par NOOP) donc on pourrait en parler au prof (ou pas)
### Ajout d'opération optionel : 
- [x] ADDIU https://www.gladir.com/CODER/ASMMIPS/addiu.htm 
- [x] ADDU https://www.gladir.com/CODER/ASMMIPS/addu.htm
- [x] ANDI https://www.gladir.com/CODER/ASMMIPS/andi.htm
- [x] BGEZ https://www.gladir.com/CODER/ASMMIPS/bgez.htm
- [x] BGEZAL https://www.gladir.com/CODER/ASMMIPS/bgezal.htm
- [x] BLTZ https://www.gladir.com/CODER/ASMMIPS/bltz.htm
- [x] BLTZAL https://www.gladir.com/CODER/ASMMIPS/bltzal.htm
- [x] DIVU https://www.gladir.com/CODER/ASMMIPS/divu.htm
- [x] LB https://www.gladir.com/CODER/ASMMIPS/lb.htm
- [x] MULTU https://www.gladir.com/CODER/ASMMIPS/multu.htm
- [x] ORI https://www.gladir.com/CODER/ASMMIPS/ori.htm
- [x] SB https://www.gladir.com/CODER/ASMMIPS/sb.htm
- [x] SLLV https://www.gladir.com/CODER/ASMMIPS/sllv.htm
- [x] SLTI https://www.gladir.com/CODER/ASMMIPS/slti.htm
- [x] SLTIU https://www.gladir.com/CODER/ASMMIPS/sltiu.htm
- [x] SLTU https://www.gladir.com/CODER/ASMMIPS/sltu.htm
- [x] SRA https://www.gladir.com/CODER/ASMMIPS/sra.htm
- [x] SRLV https://www.gladir.com/CODER/ASMMIPS/srlv.htm
- [x] SUBU https://www.gladir.com/CODER/ASMMIPS/subu.htm
- [x] XORI https://www.gladir.com/CODER/ASMMIPS/xori.htm
