### ISSUE TITLE
ToDo List Partie X 

### ISSUE THREAD

**Issue by Mangawn** [Sonkom/MIPS_3A#2]
# ToDo List Partie X 
Cette liste concerne l'implémentation future des opérations classé en trois groupe : Obligatoire , Optionelle simple, Optionelle moins simple. 

## Obligatoire 👮‍♂️ 
- [x] ADD https://www.gladir.com/CODER/ASMMIPS/add.htm
- [x] ADDI https://www.gladir.com/CODER/ASMMIPS/addi.htm
- [x] AND https://www.gladir.com/CODER/ASMMIPS/and.htm
- [x] BEQ https://www.gladir.com/CODER/ASMMIPS/beq.htm
- [x] BGTZ https://www.gladir.com/CODER/ASMMIPS/bgtz.htm
- [x] BLEZ https://www.gladir.com/CODER/ASMMIPS/blez.htm
- [x] BNE https://www.gladir.com/CODER/ASMMIPS/bne.htm
- [x] DIV https://www.gladir.com/CODER/ASMMIPS/div.htm
- [ ] J https://www.gladir.com/CODER/ASMMIPS/jump.htm
- [ ] JAL https://www.gladir.com/CODER/ASMMIPS/jal.htm
- [x] JR https://www.gladir.com/CODER/ASMMIPS/jr.htm
- [x] LUI https://www.gladir.com/CODER/ASMMIPS/lui.htm
- [x] LW https://www.gladir.com/CODER/ASMMIPS/lw.htm
- [x] MFHI https://www.gladir.com/CODER/ASMMIPS/mfhi.htm
- [x] MFLO https://www.gladir.com/CODER/ASMMIPS/mflo.htm
- [x] MULT https://www.gladir.com/CODER/ASMMIPS/mult.htm
- [x] NOP https://www.gladir.com/CODER/ASMMIPS/noop.htm
- [x] OR https://www.gladir.com/CODER/ASMMIPS/or.htm
- [x] ROTR https://www.gladir.com/CODER/ASMMIPS/rotr.htm
- [x] SLL https://www.gladir.com/CODER/ASMMIPS/sll.htm
- [x] SLT https://www.gladir.com/CODER/ASMMIPS/slt.htm
- [x] SRL https://www.gladir.com/CODER/ASMMIPS/srl.htm
- [x] SUB https://www.gladir.com/CODER/ASMMIPS/sub.htm
- [x] SW https://www.gladir.com/CODER/ASMMIPS/sw.htm
- [x] XOR https://www.gladir.com/CODER/ASMMIPS/xor.htm
## Optionelle 🤓
- [ ] ADDIU https://www.gladir.com/CODER/ASMMIPS/addiu.htm 
- [ ] ADDU https://www.gladir.com/CODER/ASMMIPS/addu.htm
- [ ] ANDI https://www.gladir.com/CODER/ASMMIPS/andi.htm
- [ ] BGEZ https://www.gladir.com/CODER/ASMMIPS/bgez.htm
- [ ] BGEZAL https://www.gladir.com/CODER/ASMMIPS/bgezal.htm
- [ ] BLTZ https://www.gladir.com/CODER/ASMMIPS/bltz.htm
- [ ] BLTZAL https://www.gladir.com/CODER/ASMMIPS/bltzal.htm
- [ ] DIVU https://www.gladir.com/CODER/ASMMIPS/divu.htm
- [ ] LB https://www.gladir.com/CODER/ASMMIPS/lb.htm
- [ ] MULTU https://www.gladir.com/CODER/ASMMIPS/multu.htm
- [ ] ORI https://www.gladir.com/CODER/ASMMIPS/ori.htm
- [ ] SB https://www.gladir.com/CODER/ASMMIPS/sb.htm
- [ ] SLLV https://www.gladir.com/CODER/ASMMIPS/sllv.htm
- [ ] SLTI https://www.gladir.com/CODER/ASMMIPS/slti.htm
- [ ] SLTIU https://www.gladir.com/CODER/ASMMIPS/sltiu.htm
- [ ] SLTU https://www.gladir.com/CODER/ASMMIPS/sltu.htm
- [ ] SRA https://www.gladir.com/CODER/ASMMIPS/sra.htm
- [ ] SRLV https://www.gladir.com/CODER/ASMMIPS/srlv.htm
- [ ] SUBU https://www.gladir.com/CODER/ASMMIPS/subu.htm
- [ ] XORI https://www.gladir.com/CODER/ASMMIPS/xori.htm
